/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public final class ScriptAlertType {
  public final static ScriptAlertType JavascriptAlert = new ScriptAlertType("JavascriptAlert", BerkeliumCppJNI.JavascriptAlert_get());
  public final static ScriptAlertType JavascriptConfirm = new ScriptAlertType("JavascriptConfirm", BerkeliumCppJNI.JavascriptConfirm_get());
  public final static ScriptAlertType JavascriptPrompt = new ScriptAlertType("JavascriptPrompt", BerkeliumCppJNI.JavascriptPrompt_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ScriptAlertType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ScriptAlertType.class + " with value " + swigValue);
  }

  private ScriptAlertType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ScriptAlertType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ScriptAlertType(String swigName, ScriptAlertType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ScriptAlertType[] swigValues = { JavascriptAlert, JavascriptConfirm, JavascriptPrompt };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

