/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
<<<<<<< HEAD
 * Version 2.0.7
=======
 * Version 2.0.8
>>>>>>> b8cebaadde5aead5da24db0db1d434ec68fdb8d1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public class SWIGTYPE_p_WidgetList__const_reverse_iterator {
  private long swigCPtr;

  protected SWIGTYPE_p_WidgetList__const_reverse_iterator(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_WidgetList__const_reverse_iterator() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_WidgetList__const_reverse_iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

