/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public class wcharWeakString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected wcharWeakString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wcharWeakString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BerkeliumCppJNI.delete_wcharWeakString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_wchar_t data() {
    long cPtr = BerkeliumCppJNI.wcharWeakString_data(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
  }

  public long length() {
    return BerkeliumCppJNI.wcharWeakString_length(swigCPtr, this);
  }

  public long size() {
    return BerkeliumCppJNI.wcharWeakString_size(swigCPtr, this);
  }

  public static wcharWeakString point_to(SWIGTYPE_p_wchar_t byteArray, long len) {
    return new wcharWeakString(BerkeliumCppJNI.wcharWeakString_point_to(SWIGTYPE_p_wchar_t.getCPtr(byteArray), len), true);
  }

  public static wcharWeakString empty() {
    return new wcharWeakString(BerkeliumCppJNI.wcharWeakString_empty(), true);
  }

  public wcharWeakString() {
    this(BerkeliumCppJNI.new_wcharWeakString(), true);
  }

}
