/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public class WindowDelegate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WindowDelegate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WindowDelegate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BerkeliumCppJNI.delete_WindowDelegate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    BerkeliumCppJNI.WindowDelegate_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    BerkeliumCppJNI.WindowDelegate_change_ownership(this, swigCPtr, true);
  }

  public WindowDelegate() {
    this(BerkeliumCppJNI.new_WindowDelegate(), true);
    BerkeliumCppJNI.WindowDelegate_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void onAddressBarChanged(Window win, charWeakString newURL) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onAddressBarChanged(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newURL), newURL); else BerkeliumCppJNI.WindowDelegate_onAddressBarChangedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newURL), newURL);
  }

  public void onStartLoading(Window win, charWeakString newURL) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onStartLoading(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newURL), newURL); else BerkeliumCppJNI.WindowDelegate_onStartLoadingSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newURL), newURL);
  }

  public void onLoad(Window win) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onLoad(swigCPtr, this, Window.getCPtr(win), win); else BerkeliumCppJNI.WindowDelegate_onLoadSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win);
  }

  public void onCrashedWorker(Window win) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onCrashedWorker(swigCPtr, this, Window.getCPtr(win), win); else BerkeliumCppJNI.WindowDelegate_onCrashedWorkerSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win);
  }

  public void onCrashedPlugin(Window win, wcharWeakString pluginName) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onCrashedPlugin(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(pluginName), pluginName); else BerkeliumCppJNI.WindowDelegate_onCrashedPluginSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(pluginName), pluginName);
  }

  public void onProvisionalLoadError(Window win, charWeakString url, int errorCode, boolean isMainFrame) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onProvisionalLoadError(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(url), url, errorCode, isMainFrame); else BerkeliumCppJNI.WindowDelegate_onProvisionalLoadErrorSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(url), url, errorCode, isMainFrame);
  }

  public void onConsoleMessage(Window win, wcharWeakString message, wcharWeakString sourceId, int line_no) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onConsoleMessage(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, wcharWeakString.getCPtr(sourceId), sourceId, line_no); else BerkeliumCppJNI.WindowDelegate_onConsoleMessageSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, wcharWeakString.getCPtr(sourceId), sourceId, line_no);
  }

  public void onScriptAlert(Window win, wcharWeakString message, wcharWeakString defaultValue, charWeakString url, int flags, SWIGTYPE_p_bool success, wcharWeakString value) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onScriptAlert(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, wcharWeakString.getCPtr(defaultValue), defaultValue, charWeakString.getCPtr(url), url, flags, SWIGTYPE_p_bool.getCPtr(success), wcharWeakString.getCPtr(value), value); else BerkeliumCppJNI.WindowDelegate_onScriptAlertSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, wcharWeakString.getCPtr(defaultValue), defaultValue, charWeakString.getCPtr(url), url, flags, SWIGTYPE_p_bool.getCPtr(success), wcharWeakString.getCPtr(value), value);
  }

  public void freeLastScriptAlert(wcharWeakString lastValue) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_freeLastScriptAlert(swigCPtr, this, wcharWeakString.getCPtr(lastValue), lastValue); else BerkeliumCppJNI.WindowDelegate_freeLastScriptAlertSwigExplicitWindowDelegate(swigCPtr, this, wcharWeakString.getCPtr(lastValue), lastValue);
  }

  public void onNavigationRequested(Window win, charWeakString newUrl, charWeakString referrer, boolean isNewWindow, SWIGTYPE_p_bool cancelDefaultAction) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onNavigationRequested(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newUrl), newUrl, charWeakString.getCPtr(referrer), referrer, isNewWindow, SWIGTYPE_p_bool.getCPtr(cancelDefaultAction)); else BerkeliumCppJNI.WindowDelegate_onNavigationRequestedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, charWeakString.getCPtr(newUrl), newUrl, charWeakString.getCPtr(referrer), referrer, isNewWindow, SWIGTYPE_p_bool.getCPtr(cancelDefaultAction));
  }

  public void onLoadingStateChanged(Window win, boolean isLoading) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onLoadingStateChanged(swigCPtr, this, Window.getCPtr(win), win, isLoading); else BerkeliumCppJNI.WindowDelegate_onLoadingStateChangedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, isLoading);
  }

  public void onTitleChanged(Window win, wcharWeakString title) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onTitleChanged(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(title), title); else BerkeliumCppJNI.WindowDelegate_onTitleChangedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(title), title);
  }

  public void onTooltipChanged(Window win, wcharWeakString text) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onTooltipChanged(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(text), text); else BerkeliumCppJNI.WindowDelegate_onTooltipChangedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(text), text);
  }

  public void onCrashed(Window win) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onCrashed(swigCPtr, this, Window.getCPtr(win), win); else BerkeliumCppJNI.WindowDelegate_onCrashedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win);
  }

  public void onUnresponsive(Window win) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onUnresponsive(swigCPtr, this, Window.getCPtr(win), win); else BerkeliumCppJNI.WindowDelegate_onUnresponsiveSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win);
  }

  public void onResponsive(Window win) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onResponsive(swigCPtr, this, Window.getCPtr(win), win); else BerkeliumCppJNI.WindowDelegate_onResponsiveSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win);
  }

  public void onExternalHost(Window win, wcharWeakString message, charWeakString origin, charWeakString target) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onExternalHost(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, charWeakString.getCPtr(origin), origin, charWeakString.getCPtr(target), target); else BerkeliumCppJNI.WindowDelegate_onExternalHostSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, wcharWeakString.getCPtr(message), message, charWeakString.getCPtr(origin), origin, charWeakString.getCPtr(target), target);
  }

  public void onCreatedWindow(Window win, Window newWindow, Rect initialRect) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onCreatedWindow(swigCPtr, this, Window.getCPtr(win), win, Window.getCPtr(newWindow), newWindow, Rect.getCPtr(initialRect), initialRect); else BerkeliumCppJNI.WindowDelegate_onCreatedWindowSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Window.getCPtr(newWindow), newWindow, Rect.getCPtr(initialRect), initialRect);
  }

  public void onPaint(Window win, SWIGTYPE_p_unsigned_char sourceBuffer, Rect sourceBufferRect, long numCopyRects, Rect[] copyRects, int dx, int dy, Rect scrollRect) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onPaint(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_unsigned_char.getCPtr(sourceBuffer), Rect.getCPtr(sourceBufferRect), sourceBufferRect, numCopyRects, copyRects, dx, dy, Rect.getCPtr(scrollRect), scrollRect); else BerkeliumCppJNI.WindowDelegate_onPaintSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_unsigned_char.getCPtr(sourceBuffer), Rect.getCPtr(sourceBufferRect), sourceBufferRect, numCopyRects, copyRects, dx, dy, Rect.getCPtr(scrollRect), scrollRect);
  }

  public void onWidgetCreated(Window win, Widget newWidget, int zIndex) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onWidgetCreated(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(newWidget), newWidget, zIndex); else BerkeliumCppJNI.WindowDelegate_onWidgetCreatedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(newWidget), newWidget, zIndex);
  }

  public void onWidgetDestroyed(Window win, Widget wid) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onWidgetDestroyed(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid); else BerkeliumCppJNI.WindowDelegate_onWidgetDestroyedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid);
  }

  public void onWidgetResize(Window win, Widget wid, int newWidth, int newHeight) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onWidgetResize(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, newWidth, newHeight); else BerkeliumCppJNI.WindowDelegate_onWidgetResizeSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, newWidth, newHeight);
  }

  public void onWidgetMove(Window win, Widget wid, int newX, int newY) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onWidgetMove(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, newX, newY); else BerkeliumCppJNI.WindowDelegate_onWidgetMoveSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, newX, newY);
  }

  public void onWidgetPaint(Window win, Widget wid, SWIGTYPE_p_unsigned_char sourceBuffer, Rect sourceBufferRect, long numCopyRects, Rect[] copyRects, int dx, int dy, Rect scrollRect) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onWidgetPaint(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, SWIGTYPE_p_unsigned_char.getCPtr(sourceBuffer), Rect.getCPtr(sourceBufferRect), sourceBufferRect, numCopyRects, copyRects, dx, dy, Rect.getCPtr(scrollRect), scrollRect); else BerkeliumCppJNI.WindowDelegate_onWidgetPaintSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, Widget.getCPtr(wid), wid, SWIGTYPE_p_unsigned_char.getCPtr(sourceBuffer), Rect.getCPtr(sourceBufferRect), sourceBufferRect, numCopyRects, copyRects, dx, dy, Rect.getCPtr(scrollRect), scrollRect);
  }

  public void onCursorUpdated(Window win, SWIGTYPE_p_Cursor newCursor) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onCursorUpdated(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_Cursor.getCPtr(newCursor)); else BerkeliumCppJNI.WindowDelegate_onCursorUpdatedSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_Cursor.getCPtr(newCursor));
  }

  public void onShowContextMenu(Window win, ContextMenuEventArgs args) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onShowContextMenu(swigCPtr, this, Window.getCPtr(win), win, ContextMenuEventArgs.getCPtr(args), args); else BerkeliumCppJNI.WindowDelegate_onShowContextMenuSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, ContextMenuEventArgs.getCPtr(args), args);
  }

  public void onJavascriptCallback(Window win, SWIGTYPE_p_void replyMsg, charWeakString origin, wcharWeakString funcName, SWIGTYPE_p_Script__Variant args, long numArgs) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onJavascriptCallback(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_void.getCPtr(replyMsg), charWeakString.getCPtr(origin), origin, wcharWeakString.getCPtr(funcName), funcName, SWIGTYPE_p_Script__Variant.getCPtr(args), numArgs); else BerkeliumCppJNI.WindowDelegate_onJavascriptCallbackSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, SWIGTYPE_p_void.getCPtr(replyMsg), charWeakString.getCPtr(origin), origin, wcharWeakString.getCPtr(funcName), funcName, SWIGTYPE_p_Script__Variant.getCPtr(args), numArgs);
  }

  public void onRunFileChooser(Window win, int mode, wcharWeakString title, charWeakString defaultFile) {
    if (getClass() == WindowDelegate.class) BerkeliumCppJNI.WindowDelegate_onRunFileChooser(swigCPtr, this, Window.getCPtr(win), win, mode, wcharWeakString.getCPtr(title), title, charWeakString.getCPtr(defaultFile), defaultFile); else BerkeliumCppJNI.WindowDelegate_onRunFileChooserSwigExplicitWindowDelegate(swigCPtr, this, Window.getCPtr(win), win, mode, wcharWeakString.getCPtr(title), title, charWeakString.getCPtr(defaultFile), defaultFile);
  }

}
