/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public class BerkeliumCpp {
  public static boolean init(charWeakString homeDirectory, charWeakString subprocessDirectory, long extra_argc, SWIGTYPE_p_p_char extra_argv) {
    return BerkeliumCppJNI.init__SWIG_0(charWeakString.getCPtr(homeDirectory), homeDirectory, charWeakString.getCPtr(subprocessDirectory), subprocessDirectory, extra_argc, SWIGTYPE_p_p_char.getCPtr(extra_argv));
  }

  public static boolean init(charWeakString homeDirectory, charWeakString subprocessDirectory, long extra_argc) {
    return BerkeliumCppJNI.init__SWIG_1(charWeakString.getCPtr(homeDirectory), homeDirectory, charWeakString.getCPtr(subprocessDirectory), subprocessDirectory, extra_argc);
  }

  public static boolean init(charWeakString homeDirectory, charWeakString subprocessDirectory) {
    return BerkeliumCppJNI.init__SWIG_2(charWeakString.getCPtr(homeDirectory), homeDirectory, charWeakString.getCPtr(subprocessDirectory), subprocessDirectory);
  }

  public static void destroy() {
    BerkeliumCppJNI.destroy();
  }

  public static void update() {
    BerkeliumCppJNI.update();
  }

  public static SWIGTYPE_p_unsigned_char new_ucharArray(int nelements) {
    long cPtr = BerkeliumCppJNI.new_ucharArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static void delete_ucharArray(SWIGTYPE_p_unsigned_char ary) {
    BerkeliumCppJNI.delete_ucharArray(SWIGTYPE_p_unsigned_char.getCPtr(ary));
  }

  public static short ucharArray_getitem(SWIGTYPE_p_unsigned_char ary, int index) {
    return BerkeliumCppJNI.ucharArray_getitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index);
  }

  public static void ucharArray_setitem(SWIGTYPE_p_unsigned_char ary, int index, short value) {
    BerkeliumCppJNI.ucharArray_setitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index, value);
  }

}
