/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package berkelium;

public final class FileChooserType {
  public final static FileChooserType FileOpen = new FileChooserType("FileOpen", BerkeliumCppJNI.FileOpen_get());
  public final static FileChooserType FileOpenMultiple = new FileChooserType("FileOpenMultiple", BerkeliumCppJNI.FileOpenMultiple_get());
  public final static FileChooserType FileOpenFolder = new FileChooserType("FileOpenFolder", BerkeliumCppJNI.FileOpenFolder_get());
  public final static FileChooserType FileSaveAs = new FileChooserType("FileSaveAs", BerkeliumCppJNI.FileSaveAs_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FileChooserType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FileChooserType.class + " with value " + swigValue);
  }

  private FileChooserType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FileChooserType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FileChooserType(String swigName, FileChooserType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FileChooserType[] swigValues = { FileOpen, FileOpenMultiple, FileOpenFolder, FileSaveAs };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

